name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Cypress
        uses: cypress-io/github-action@v7
        with:
          cypress-version: ^12.0.0
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v7
        with:
          start: npx cypress run 